# Generated by Django 3.1 on 2020-08-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('attributes', models.JSONField()),
            ],
        ),
    ]
